<?php

?>
<script>
    require(['uiRegistry'], function() {
     var strPages  = document.getElementById('linkpages');

     var checkedPages = strPages.value.split(',');

     for(let i=0 ;i< checkedPages.length; i++ ){
         let id = 'id_'+checkedPages[i];
         if(null!= document.getElementById(id)){
             document.getElementById(id).checked = true;
         }
     }

     var checkboxes = document.getElementsByClassName('admin__control-checkbox');
     for (let i=0;i<checkboxes.length;i++) {

         checkboxes[i].addEventListener( 'change', function() {
             if(this.checked) {
                checkedPages.push(this.value);
                 strPages = checkedPages.join(',');

             } else {
                 for(let i=0;i<checkedPages.length;i++){
                     if(+checkedPages[i] === +this.value){
                       checkedPages.splice(i,1);
                       strPages = checkedPages.join(',');
                         break;
                     }
                 }
             }
             document.getElementById('linkpages').value = strPages;
         });
     }


    })
</script>